### ISSUE TITLE
Not working on 0.5.1

### ISSUE THREAD

**Issue by jayzalowitz** [martinlindenberg/serverless-plugin-alerting#5]
C02PH09LG3QN:tlscm jzalowitz$ sls function deploy
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Class extends value #<Serverless> is not a function or null
    at module.exports (/Users/jzalowitz/Sites/tlscm/tlscm/node_modules/serverless-plugin-alerting/index.js:10:44)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by martinlindenberg** [comment]
new release created
published to npm

should work now
